import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { ROUTES } from '@/constants/routes';

export default function Home() {
    const router = useRouter();
    useEffect(() => {
        router.push(ROUTES.DEFAULT);
    }, [router]);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}></main>
        </>
    );
}
